{
 "title": "Service details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(latency_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"${service}\"} [$__rate_interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(latency_count{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"} [$__rate_interval])) by (service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"${service}\"} [$__rate_interval])) by (service_name, le))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Downstream services",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(traces_service_graph_request_total{client=\"${service}\"} [$__rate_interval])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}