apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: webstore-tempo
    typeName: Tempo
    typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
    access: proxy
    url: http://tempo:3200
    user: ""
    database: ""
    basicAuth: false
    readOnly: false
    jsonData:
      maxLines: 1000
      serviceMap:
        datasourceUid: webstore-metrics
      search:
        hide: false
      nodeGraph:
        enabled: true
