global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: otel
    static_configs:
      - targets:
          - "otelcol:9464"
  - job_name: otel-collector
    static_configs:
      - targets:
          - "otelcol:8888"
  - job_name: grafana-agent
    static_configs:
      - targets:
          - "grafana-agent:12345"
