# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  fluentforward:
    endpoint: otelcol:24224

exporters:
  logging:
    verbosity: detailed
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  # TODO spanmetrics does not work correctly with prometheus exporter, until it is fixed we will
  # use prometheusremotewrite instead
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  attributes:
    actions:
      - action: insert
        key: service.name
        from_attribute: container_name
      - action: insert
        key: service.namespace
        value: opentelemetry-demo
      - action: insert
        key: service.instance.id
        from_attribute: container_id
      - action: insert
        key: service_name
        from_attribute: container_name
      - action: insert
        key: loki.attribute.labels
        value: service_name

  groupbyattrs:
    keys:
      - service.name
      - service.namespace
      - service.instance.id

  transform/grafanacloudapm:
    trace_statements:
      - context: span
        statements:
          - replace_match(attributes["http.target"], "/api/products/*", "/api/products/{productId}")
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP GET" and attributes["http.target"] != nil
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP POST" and attributes["http.target"] != nil
  transform/fluentd:
    log_statements:
      - context: log
        statements:
          - replace_pattern(attributes["container_name"], "^/", "")
          - replace_pattern(attributes["container_name"], "\\-", "")
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [transform/grafanacloudapm, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp, fluentforward]
      processors: [transform/fluentd, attributes, groupbyattrs]
      exporters: [loki]
