# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  fluentforward:
    endpoint: otelcol:24224

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "otelcol:9464"
    enable_open_metrics: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  attributes:
    actions:
      - action: insert
        key: service_name
        from_attribute: container_name
      - action: insert
        key: loki.attribute.labels
        value: service_name

  transform/grafanacloudapm:
    trace_statements:
      - context: span
        statements:
          - replace_match(attributes["http.target"], "/api/products/*", "/api/products/{productId}")
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP GET" and attributes["http.target"] != nil
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP POST" and attributes["http.target"] != nil
  transform/fluentd:
    log_statements:
      - context: log
        statements:
          - replace_pattern(attributes["container_name"], "^/", "")
          - replace_pattern(attributes["container_name"], "\\-", "")
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: process.runtime.name
        default: UNSET
      - name: telemetry.sdk.language
        default: UNSET
  servicegraph:
    metrics_exporter: prometheus
  filter:
    error_mode: ignore
    traces:
      span:
        # filter out internal spans
        - 'kind == 1'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter, transform/grafanacloudapm, spanmetrics, servicegraph, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp, fluentforward]
      processors: [transform/fluentd, attributes]
      exporters: [loki]
