# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
extensions:
  basicauth/grafanacloud:
    client_auth:
      username: ${GRAFANA_INSTANCE_ID}
      password: ${GRAFANA_CLOUD_APIKEY}
  basicauth/grafanacloud-mimir:
    client_auth:
      username: ${GRAFANA_MIMIR_INSTANCE_ID}
      password: ${GRAFANA_CLOUD_APIKEY}

exporters:
  prometheusremotewrite:
    endpoint: ${GRAFANA_MIMIR_ENDPOINT}
    auth:
      authenticator: basicauth/grafanacloud-mimir
  otlphttp/grafanacloud:
    auth:
      authenticator: basicauth/grafanacloud
    endpoint: ${GRAFANA_OTLP_ENDPOINT}

service:
  extensions: [basicauth/grafanacloud, basicauth/grafanacloud-mimir]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/grafanacloud, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus, prometheusremotewrite, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/grafanacloud]
