---
kind: pipeline
type: docker
name: docker-push
steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    repo: integration-artifacts/otel-demo-frontend
    tags: latest
    context: /src/frontend/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
trigger:
  event:
    include:
    - push

---
kind: secret
name: gcp_key

get:
    name: gcp_key
    path: infra/data/ci/drone-plugins
---
kind: secret
name: gh_token

get:
  name: pat
  path: infra/data/ci/github/grafanabot
---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: signature
hmac: 0bd918abdb02f4cbe034bc2a08eda24a2fd1ebbec39836ab95aa66b7fd4f2cae

...
