---
kind: pipeline
type: docker
name: docker-push

trigger:
  event:
    include:
    - push

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: integration-artifacts/otel-demo-frontend
    tags: latest
    context: ./src/frontend/
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

---
kind: secret
name: gcp_key

get:
    name: gcp_key
    path: infra/data/ci/drone-plugins
---
kind: secret
name: gh_token

get:
  name: pat
  path: infra/data/ci/github/grafanabot
---
kind: secret
name: dockerconfigjson

get:
  path: secret/data/common/gcr
  name: .dockerconfigjson

---
kind: signature
hmac: 1cc8ac1e3aacbe31df1534072737437e17fbcfdf0dbff4e09eaca2519e117b1e

...
